In [1]:
import numpy as np

## inner product(내적)

In [12]:
A = np.array([[1, 3],[2, 5]])
B = np.array([1, 1])

In [16]:
np.dot(A,B) # 각 행에 B 가 곱해짐

array([4, 7])

In [17]:
np.dot(A.T, B)

array([3, 8])

## Training algorithm (OR problem)

In [18]:
W = np.array([-0.5, 0.75])
b = 0.375

In [20]:
# 입력과 정답 정의
x0 = np.array([0, 0])
x1 = np.array([1, 0])
x2 = np.array([0, 1])
x3 = np.array([1, 1])
t0 = -1
t1 =  1
t2 =  1
t3 =  1

In [21]:
# 입력과 정답 정의 (간단)
X = np.array([x0, x1, x2, x3])
T = np.array([t0, t1 , t2, t3])

In [23]:
X, T

(array([[0, 0],
        [1, 0],
        [0, 1],
        [1, 1]]),
 array([-1,  1,  1,  1]))

In [27]:
# 출력 계산
y1 = np.dot(W, x0) + b # A    
y2 = np.dot(W, x1) + b # B    
y3 = np.dot(W, x2) + b # C   
y4 = np.dot(W, x3) + b # D    

print(y1, y2, y3, y4)

0.375 -0.125 1.125 0.625


In [28]:
# 출력 계산 (간단)
y = np.dot(X,W) + b
print(y)

[ 0.375 -0.125  1.125  0.625]


In [34]:
# 교재 외 구현 (출력)
z = np.ones(y.shape)
z[y<0.0] =-1
z

array([ 1., -1.,  1.,  1.])

### 퍼셉트론 구현 (교재 p.6 참고)

In [120]:
# 재정의
W = np.array([-0.5, 0.75])
b = 0.375

# 입력과 정답 정의
x0 = np.array([0, 0])
x1 = np.array([1, 0])
x2 = np.array([0, 1])
x3 = np.array([1, 1])
t0 = -1
t1 =  1
t2 =  1
t3 =  1

Xset = np.array([x0, x1, x2, x3])
T = np.array([t0, t1 , t2, t3])

In [121]:
def perceptron_1(W,x,b):
    y =  np.dot(W,x) + b
    if y >= 0.0: z = 1
    else:        z = -1
    return y,z

In [122]:
def perceptorn_predict(W,Xset,b):
    y_set = []
    z_set = []

    for x in Xset:
        y, z = perceptron_1(W,x,b)
        y_set.append(y)
        z_set.append(z)
    return y_set, z_set


In [123]:
y_s, z_s = perceptorn_predict(W, Xset, b)

In [124]:
z_s, T

([1, -1, 1, 1], array([-1,  1,  1,  1]))

In [125]:
Y_incorrect = z_s != T

In [126]:
Y_incorrect

array([ True,  True, False, False])

### zip함수

In [127]:
# zip 함수
list(zip(Xset,T))

[(array([0, 0]), -1),
 (array([1, 0]), 1),
 (array([0, 1]), 1),
 (array([1, 1]), 1)]

In [128]:
for x, t_i in zip(Xset,T):
    print(x,t_i)

[0 0] -1
[1 0] 1
[0 1] 1
[1 1] 1


### 계속 구현

In [129]:
alpha = 0.4

# np.count_nonzero() 함수
if np.count_nonzero(Y_incorrect) != 0:
    delta_w = 0.0
    delta_b = 0.0
 
    # update W, b
    for flag, ti, xi in zip(Y_incorrect, T, Xset):
        if flag == True:
            delta_w += ti * xi
            delta_b += ti

    delta_w = alpha * delta_w
    delta_b = alpha * delta_b

    W = W + delta_w
    b = b + delta_b

    print(delta_w, delta_b, W, b) # W, b가 업데이트 됨

[0.4 0. ] 0.0 [-0.1   0.75] 0.375


#### 반복

In [130]:
# 다시 예측 (업데이트 된  W , b 이용)
y_s, z_s = perceptorn_predict(W, Xset, b)
print(y_s, z_s)

[0.375, 0.275, 1.125, 1.025] [1, 1, 1, 1]


In [131]:
Y_incorrect = z_s != T
print(Y_incorrect)

[ True False False False]


## 직선이 나올때 까지 반복

In [153]:
# 재정의
W = np.array([-0.5, 0.75])
b = 0.375

# 입력과 정답 정의
Xset = np.array([[0, 0],[1, 0],[0, 1],[1, 1]])
T = np.array([-1, 1, 1, 1])

In [154]:
iter = 0

for i in np.arange(100):
    # 예측
    y_s, z_s = perceptorn_predict(W, Xset, b)    
    Y_incorrect = z_s != T

    # count up
    iter += 1
    
       # 여전히 오류가 존재하는 경우
    if np.count_nonzero(Y_incorrect) != 0:
        delta_w = 0.0
        delta_b = 0.0
     
        # update W, b
        for flag, ti, xi in zip(Y_incorrect, T, Xset):
            if flag == True:
                delta_w += ti * xi
                delta_b += ti
    
        delta_w = alpha * delta_w
        delta_b = alpha * delta_b
    
        W = W + delta_w
        b = b + delta_b

        print(iter, delta_w, delta_b, W, b, Y_incorrect)

    else:
         # 오류가 없을 경우    
        print(iter, delta_w, delta_b, W, b, Y_incorrect)
        break 

1 [0.4 0. ] 0.0 [-0.1   0.75] 0.375 [ True  True False False]
2 [0. 0.] -0.4 [-0.1   0.75] -0.025000000000000022 [ True False False False]
3 [0.4 0. ] 0.4 [0.3  0.75] 0.375 [False  True False False]
4 [0. 0.] -0.4 [0.3  0.75] -0.025000000000000022 [ True False False False]
5 [0. 0.] -0.4 [0.3  0.75] -0.025000000000000022 [False False False False]
