## __Redefinition in class__

### str()

In [4]:
class Point2D:
    def __init__(self,x,y):
        self.x = x
        self.y = y
    def PrintPt(self):
        print(f'({self.x}, {self.y})') 

In [7]:
p1 = Point2D(3,5)
p2 = Point2D(-1,-2)

In [8]:
print(p1)
print(p1.x, p1.y)
p1.PrintPt()

3 5
(3, 5)


In [18]:
class Point2D:
    def __init__(self,x,y):
        self.x = x
        self.y = y
    def __str__(self):
        return f'({self.x}, {self.y})' 

In [19]:
p3 = Point2D(3,5)
p4 = Point2D(-1,-2)

In [20]:
print(p3)

(3, 5)


### add()

In [26]:
class Point2D:
    def __init__(self,x,y):
        self.x = x
        self.y = y
    def __str__(self):
        return f'({self.x}, {self.y})' 
    def Add(self,pt):
        return Point2D(self.x + pt.x, self.y + pt.y)

In [27]:
p3 = Point2D(3,5)
p4 = Point2D(-1,-2)

In [29]:
p5 = p3.Add(p4)
print(p5)

(2, 3)


In [34]:
class Point2D:
    def __init__(self,x,y):
        self.x = x
        self.y = y
    def __str__(self):
        return f'({self.x}, {self.y})' 
    def __add__(self,pt):
        new_x = self.x + pt.x
        new_y = self.y + pt.y
        return Point2D(new_x, new_y)

In [35]:
p3 = Point2D(3,5)
p4 = Point2D(-1,-2)

In [38]:
p6 = p3 + p4  # p3.__add(p4)__
print(p6)

(2, 3)


### sub()

In [39]:
class Point2D:
    def __init__(self,x,y):
        self.x = x
        self.y = y
    def __str__(self):
        return f'({self.x}, {self.y})' 
    def __add__(self,pt):
        new_x = self.x + pt.x
        new_y = self.y + pt.y
        return Point2D(new_x, new_y)
    def __sub__(self,pt):
        new_x = self.x - pt.x
        new_y = self.y - pt.y
        return Point2D(new_x, new_y)

In [40]:
p3 = Point2D(3,5)
p4 = Point2D(-1,-2)

In [41]:
p7 = p3 - p4
print(p7)

(4, 7)


## __Practice__

### ComplexNumber

In [64]:
class ComplexNumber:
    def __init__(self, real, img):
        self.real = real
        self.img = img
        
    def __str__(self):
        if self.img>=0:
            return f'{self.real}+j{self.img}'
        else:
            return f'{self.real}-j{-self.img}'
        
    def __add__(self,pt):
        return ComplexNumber(self.real + pt.real, self.img + pt.img)
        
    def __sub__(self,pt):
        return ComplexNumber(self.real - pt.real, self.img - pt.img)
        
    def __mul__(self,pt):
        new_real = self.real * pt.real - self.img * pt.img
        new_img = self.real * pt.img + self.img * pt.real
        return ComplexNumber(new_real, new_img)

In [65]:
a = ComplexNumber(1,2)
b = ComplexNumber(-3,3)

In [66]:
c = a + b
d = a - b
e = a * b

In [67]:
print(a, b, sep =',   ')
print(c, d, e, sep =',   ')

1+j2,   -3+j3
-2+j5,   4-j1,   -9-j3


## __정규표현식__

### __Numpy__

### Tensor

In [68]:
import numpy as np

In [70]:
arr = np.array(5) # numpy의 num은 숫자를 의미 -> np.array에는 숫자만 들어간다.

In [71]:
arr.shape # 0 dimention, scalr 5

()

In [73]:
arr1 = np.array([1,2,3])
arr1

array([1, 2, 3])

In [74]:
arr1.shape # 1차원

(3,)

In [76]:
arr2 = np.array([arr1, arr1, arr1, arr1])
arr2

array([[1, 2, 3],
       [1, 2, 3],
       [1, 2, 3],
       [1, 2, 3]])

In [77]:
arr2.shape # 2차원

(4, 3)

In [79]:
arr3 = np.array([arr2, arr2])
arr3

array([[[1, 2, 3],
        [1, 2, 3],
        [1, 2, 3],
        [1, 2, 3]],

       [[1, 2, 3],
        [1, 2, 3],
        [1, 2, 3],
        [1, 2, 3]]])

In [80]:
arr3.shape # 3차원

(2, 4, 3)

In [81]:
arr4 = np.array([arr3, arr3, arr3])
arr4

array([[[[1, 2, 3],
         [1, 2, 3],
         [1, 2, 3],
         [1, 2, 3]],

        [[1, 2, 3],
         [1, 2, 3],
         [1, 2, 3],
         [1, 2, 3]]],


       [[[1, 2, 3],
         [1, 2, 3],
         [1, 2, 3],
         [1, 2, 3]],

        [[1, 2, 3],
         [1, 2, 3],
         [1, 2, 3],
         [1, 2, 3]]],


       [[[1, 2, 3],
         [1, 2, 3],
         [1, 2, 3],
         [1, 2, 3]],

        [[1, 2, 3],
         [1, 2, 3],
         [1, 2, 3],
         [1, 2, 3]]]])

In [82]:
arr4.shape # 4차원

(3, 2, 4, 3)

In [84]:
print(arr4.shape[0], arr4.shape[1], arr4.shape[2], arr4.shape[3])  # shape의 index

3 2 4 3


#### zeros(), ones()

In [92]:
zeros = np.zeros([3,4])
print(zeros)
print(zeros.shape)

[[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]
(3, 4)


In [93]:
ones = np.ones([3,4])
print(ones)
print(ones.shape)

[[1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]]
(3, 4)


In [98]:
# 대각 행렬
eye = np.eye(N = 3, M = 5)
print(eye)
print(eye.shape)

[[1. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0.]
 [0. 0. 1. 0. 0.]]
(3, 5)


### arange()

In [108]:
arr = np.arange(0,10,2)
print(arr.shape)
print(arr)

(5,)
[0 2 4 6 8]


In [113]:
arr1 = np.arange(12)
print(arr1.shape)
print(arr1)

(12,)
[ 0  1  2  3  4  5  6  7  8  9 10 11]


In [114]:
arr2 = arr1.reshape(3,4)
print(arr2.shape)
print(arr2)

(3, 4)
[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]


### indexing, slicing

In [112]:
arr2[1][2]    # 방법 1

6

In [115]:
arr2[1,2]     # 방법 2 : 더 많이 씀

6

In [116]:
arr2[1:]

array([[ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [117]:
arr2[:,1:]

array([[ 1,  2,  3],
       [ 5,  6,  7],
       [ 9, 10, 11]])

In [123]:
sarr = arr2[1:3, 2:4]

In [124]:
sarr[0,0] = 100  # sarr을 바꿨는데 arr2가 바뀜!!!
print(arr2)

[[100   1   2   3]
 [  4   5 100   7]
 [  8   9  10  11]]
