<a href="https://colab.research.google.com/github/dhkdsns20/Deep-Learning/blob/main/Midterm_23.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
a, b = 3, 3
print(a > b, a >= b, a % b, a ** b, type(a))


False True 0 27 <class 'int'>


In [2]:
a, b = 'hello', 'hello "world"'
print(a, b, a[-1], a[1], a.upper(),sep='*')

hello*hello "world"*o*e*HELLO


In [3]:
a = 'hello'.replace('h', 'hhh').upper()
print(a)


HHHELLO


In [4]:
b = 'hello "world"'
print(b[:], b[:2], b[1:3], b[3:3])


hello "world" he el 


In [5]:
c = 1, 2, 3
d = list(c)
print(c,d)

(1, 2, 3) [1, 2, 3]


In [6]:
a = [1, 2, 3, 4, 5]
a.remove(2)
print(a)

[1, 3, 4, 5]


In [8]:
b = 4
c = b in a
print(c)

True


In [9]:
a = {100: 2, 200: 3, 300: 'seoul', 0: 'korea'}
print(type(a), a[0], a.keys(), a.values())

<class 'dict'> korea dict_keys([100, 200, 300, 0]) dict_values([2, 3, 'seoul', 'korea'])


In [13]:
a = {1: 2, 3: 4, 5: 6, 7: 8}
c = 2 in a
print(c,a.get(3))

False 4


In [14]:
y = 0
for x in range(10):
    y += x
print(x,y)

9 45


In [15]:
a = list(range(3, 10))
print(a)

[3, 4, 5, 6, 7, 8, 9]


In [16]:
a = [100, 200, 300, 400]
for x in a:
  if x>100:
    continue
  print(x)

100


In [17]:
a = {1:2, 3:4, 5:6, 7:8}
for x in a:
    print(x)

1
3
5
7


In [18]:
a = {1:2, 3:4, 5:6, 7:8}
for x in a.items():
    print(x)

(1, 2)
(3, 4)
(5, 6)
(7, 8)


In [19]:
a = {1:2, 3:4, 5:6, 7:8}
for x in enumerate(a):
    print(x)

(0, 1)
(1, 3)
(2, 5)
(3, 7)


In [21]:
def fun(x, y, z=1):
    return x+y+z, x-y-z
print(fun(1,2),fun(1,2,3),fun(y=2,x=1))

(4, -2) (6, -4) (4, -2)


In [22]:
def test(*args):
    for x in args:
      print(x)
test(1,2,3, '123')

1
2
3
123


In [26]:
f = lambda x, y: x + y
print(f(10,f(10,20)))

40


In [27]:
a=[1,2,3,4,5]
b = list(map(lambda n: n%2==0, a))
print(b)

[False, True, False, True, False]


In [28]:
a=[1,2,3,4,5]
b = list(filter(lambda n: n%2==0, a))
print(b)

[2, 4]


In [29]:
import numpy as np
a =np.array([[1],[2],[3]])
b =np.array([[1,2],[3,4],[5,6]])
print(a.shape, b.shape, b[0,1])

(3, 1) (3, 2) 2


In [31]:
a = np.ones((3,2)) * 5
print(a)

[[5. 5.]
 [5. 5.]
 [5. 5.]]


In [35]:
a = np.ones((3,2)).reshape(-1)+5
print(a)

[1. 1. 1. 1. 1. 1.]


In [37]:
a = np.array([[1,2],[3,4],[5,6]])
a[a>=4] = 0
print(a)

[[1 2]
 [3 0]
 [0 0]]


In [44]:
a = np.array([[1,2],[3,4],[5,6]])
b = np.expand_dims(a,0)
c = np.expand_dims(a,1)
d = np.expand_dims(a,-1)
print(b.shape, c.shape, d.shape)
print(b,'\n', c,'\n',d)

(1, 3, 2) (3, 1, 2) (3, 2, 1)
[[[1 2]
  [3 4]
  [5 6]]] 
 [[[1 2]]

 [[3 4]]

 [[5 6]]] 
 [[[1]
  [2]]

 [[3]
  [4]]

 [[5]
  [6]]]


In [48]:
ex = np.ones(5)
print(ex.shape)

(5,)


In [50]:
print(ex)

[1. 1. 1. 1. 1.]
